FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app

WORKDIR /src
COPY ["*.csproj", "Integrador Bacen/"]
RUN echo $(ls -1 /app/source)
RUN dotnet restore "Integrador Bacen/Integrador Bacen.csproj"


COPY . ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/Integrador Bacen.dll"]